apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: friend-net
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres         # REPLACE before production
  POSTGRES_DB: auth_service_new
