apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: friend-net
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # headless — StatefulSet pod gets stable DNS: postgres-0.postgres.friend-net
