apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: friend-net
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None  # headless для StaefulSet
