services:

  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-proxy
    privileged: true # Нужно для корректной работы с SELinux на Fedora
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
    environment:
      # Разрешаем только то, что нужно Traefik
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - NETWORKS=1
      - NODES=1
      - POST=0 # Запрещаем любые изменения (создание, удаление) через API
    networks:
      - traefik-net
  traefik:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # Сокет больше НЕ НУЖЕН. Оставляем только конфиги.
      - ./traefik.yml:/etc/traefik/traefik.yml:ro,z
      - ./dynamic:/etc/traefik/dynamic:ro,z
    depends_on:
      - docker-proxy
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true