entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

# Логи доступа (покажут каждый запрос и 500-ку)
accessLog:
  format: common # или json

providers:
  docker:
    # Заменяем unix сокет на HTTP адрес прокси
    endpoint: "http://docker-proxy:2375"
    exposedByDefault: false
    network: "traefik-net"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true