services:
  kafka:
    image: apache/kafka:latest # Свежая и стабильная версия
    container_name: kafka
    environment:
      # Обязательные параметры для режима KRaft
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      # Идентификатор кластера (обязателен для запуска)
      - KAFKA_KRAFT_CLUSTER_ID=5L6g3nShT-eMCtK--X86sw
      # Настройки репликации для одного узла
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    networks:
      - traefik-net
    volumes:
      - kafka_data:/bitnami/kafka

  # Утилита для просмотра сообщений через браузер (опционально, но мега-удобно)
  kafka-ui:
    image: docker.io/kafbat/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kafkaui.rule=Host(`kafka.localhost`)"
      - "traefik.http.services.kafkaui.loadbalancer.server.port=8080"

volumes:
  kafka_data:

networks:
  traefik-net:
    external: true