apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: friend-net
data:
  APP_ENV: production
  HTTP_ADDR: ":8081"
  MONGO_URI: "mongodb://mongodb:27017"
  MONGO_DATABASE: user_service
  MONGO_TIMEOUT: "10s"
  KAFKA_ENABLED: "true"
  KAFKA_BROKERS: "kafka.friend-net.svc.cluster.local:9092"
  KAFKA_TOPIC: accounts.events
  KAFKA_GROUP_ID: user-service
  LOG_LEVEL: info
