services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - "8081:8080"
    env_file:
    - .env
    environment:
    - POSTGRES_HOST=postgres
    - REDIS_ADDR=redis:6379
    - KAFKA_BROKERS=kafka:9092
    - GOOGLE_REDIRECT_URL=http://localhost/auth/google/callback
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - auth-network
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.auth-public.rule=Host(`localhost`) && PathPrefix(`/auth/register`, `/auth/login`, `/auth/refresh`, `/auth/introspect`, `/auth/google`, `/healthz`)"
      - "traefik.http.routers.auth-public.entrypoints=web"
      - "traefik.http.routers.auth-private.rule=Host(`localhost`) && PathPrefix(`/auth/logout`, `/auth/sessions`, `/auth/link`)"
      - "traefik.http.routers.auth-private.entrypoints=web"
      - "traefik.http.routers.auth-private.middlewares=jwt-auth@file"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"

  postgres:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_service_new
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tools/migrations:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

volumes:
  postgres_data:
  redis_data:

networks:
  auth-network:
    driver: bridge
  traefik-net:
    external: true
