env: local

server:
  httpAddr: ":8081"
  shutdownTimeout: 10s

mongo:
  uri: "mongodb://localhost:27017"
  database: "user_service"
  timeout: 10s

kafka:
  brokers:
    - "localhost:9092"
  topic: "accounts.events"
  groupId: "user-service"
  enabled: true

logger:
  level: "info"
